site_name: RxConf
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    primary: pink

nav:
  - Home: index.md
  - Development:
      - Contributing: development/contributing.md
      - Setup: development/setup.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite

repo_name: realkarych/rxconf
repo_url: https://github.com/realkarych/rxconf

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/realkarych/rxconf
      position: header
