site_name: RxConf
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    primary: pink

nav:
  - Home: index.md
  - Development:
      - Contributing: development/CONTRIBUTING.md

plugins:
  - search
