name: Run tests

on:
  push:

jobs:
  run_tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13.0-beta.4', 'pypy-3.9']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-tests.txt

      - name: Run tests on Linux and macOS
        if: runner.os != 'Windows'
        run: |
          find tests -name "test*.py" -exec python -m unittest {} +

      - name: Run tests on Windows
        if: runner.os == 'Windows'
        run: |
          pwsh -command "Get-ChildItem -Recurse -Filter 'test*.py' -Path 'tests' | ForEach-Object { python -m unittest $_.FullName }"
