name: Run tests

on:
  push:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-tests.txt

      - name: Run tests
        run: |
          find tests -name "test*.py" -exec python -m unittest {} +
